### Root route GET http request
GET http://localhost:3000/


### Test public api
GET http://localhost:3000/api/test/all


### Test signup
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "username": "joelwang.98",
    "password": "fighting45",
    "role": "sysadmin",
    "email": "joelwang.98@gmail.com"
}

### Test signin
POST http://localhost:3000/api/auth/signin
  Content-Type: application/json

{
    "username": "joelwang.98",
    "password": "fighting45"
}


### Test jwt token
GET http://localhost:3000/api/test/sysadmin
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJqb2Vsd2FuZy45OCIsInJvbGUiOiJzeXNhZG1pbiIsImlhdCI6MTc0MjMxNDA2MCwiZXhwIjoxNzQyMzE1ODYwfQ.pKNxSP34_jSyrTb3LEbDNXWaSYrnJikjghb8TiCu-JY 
Content-Type: application/json

{
    "username": "joelwang.98@gmail.com"
}
